---
- hosts: all
  tasks:
    - name: 修改ssh配置文件的安全选项
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - {
            regexp: "^PasswordAuthentication",
            line: "PasswordAuthentication no"
        }
        - {
            regexp: "^PermitRootLogin",
            line: "PermitRootLogin no"
        }
        - {
            regexp: "^Port",
            line: "Port 2849"
        }
      notify: restart ssh

  handlers:
    - name: restart ssh
      service: name=ssh state=restarted
